name: 'Secrets Scanner'
description: 'Scans repository code for exposed secrets, API keys, and sensitive information using advanced pattern matching'
author: 'Vercel Labs'
inputs:
  github-token:
    description: 'GitHub token for API access and commenting'
    required: true
  scan-path:
    description: 'Path to scan for secrets (relative to repository root)'
    required: false
    default: '.'
  exclude-paths:
    description: 'Comma-separated list of paths to exclude from scanning'
    required: false
    default: 'node_modules,.git,dist,build'
  fail-on-detection:
    description: 'Whether to fail the action if secrets are detected'
    required: false
    default: 'true'
  comment-pr:
    description: 'Whether to comment on PR with findings (only for pull_request events)'
    required: false
    default: 'true'
  severity-threshold:
    description: 'Minimum severity level to report (low, medium, high, critical)'
    required: false
    default: 'medium'
  custom-patterns:
    description: 'JSON string of custom regex patterns to scan for'
    required: false
    default: '{}'
outputs:
  secrets-found:
    description: 'Number of secrets detected'
  report-file:
    description: 'Path to the generated JSON report file'
  sarif-file:
    description: 'Path to the generated SARIF report file'
  has-secrets:
    description: 'Whether any secrets were found (true/false)'
runs:
  using: 'node20'
  main: 'main.js'
branding:
  icon: 'shield'
  color: 'red'